const AudioManager = {
  sounds: {},
  music: null,
  
  init() {
    // 효과음 로드
    this.loadSound('shoot', 'data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA//tQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAeAAAcLgAHBw4ODhYWFh0dHSUlJS0tLTQ0NDw8PEVFRUFFRUVNTU1VVVVdXV1lZWVtbW11dXV9fX2FhYWNjY2VlZWdnZ2lpaWtra21tbW9vb3FxcXNzc3V1dXd3d3l5eXt7e319fX9/f0FBQUNDQUVFRUdHR0lJSUtLS01NTU9PT1FRUVJSUlRUVFVVVVXV1dZWVlbW1tdXV1fX19hYWFjY2NlZWVnZ2dpbAAAAAAAAAAAAAAAAAAAAAAA//tQZAAA/wAAP8AAAAIAAAP8AAAAQAAAP8AAAAIAAAP8AAAAQ');
    this.loadSound('hit', 'data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA//tQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAeAAAcLgAHBw4ODhYWFh0dHSUlJS0tLTQ0NDw8PEVFRUFFRUVNTU1VVVVdXV1lZWVtbW11dXV9fX2FhYWNjY2VlZWdnZ2lpaWtra21tbW9vb3FxcXNzc3V1dXd3d3l5eXt7e319fX9/f0FBQUNDQUVFRUdHR0lJSUtLS01NTU9PT1FRUVJSUlRUVFVVVVXV1dZWVlbW1tdXV1fX19hYWFjY2NlZWVnZ2dpbAAAAAAAAAAAAAAAAAAAAAAA//tQZAAA/wAAP8AAAAIAAAP8AAAAQAAAP8AAAAIAAAP8AAAAQ');
    this.loadSound('reload', 'data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA//tQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAeAAAcLgAHBw4ODhYWFh0dHSUlJS0tLTQ0NDw8PEVFRUFFRUVNTU1VVVVdXV1lZWVtbW11dXV9fX2FhYWNjY2VlZWdnZ2lpaWtra21tbW9vb3FxcXNzc3V1dXd3d3l5eXt7e319fX9/f0FBQUNDQUVFRUdHR0lJSUtLS01NTU9PT1FRUVJSUlRUVFVVVVXV1dZWVlbW1tdXV1fX19hYWFjY2NlZWVnZ2dpbAAAAAAAAAAAAAAAAAAAAAAA//tQZAAA/wAAP8AAAAIAAAP8AAAAQAAAP8AAAAIAAAP8AAAAQ');
    this.loadSound('jump', 'data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA//tQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAeAAAcLgAHBw4ODhYWFh0dHSUlJS0tLTQ0NDw8PEVFRUFFRUVNTU1VVVVdXV1lZWVtbW11dXV9fX2FhYWNjY2VlZWdnZ2lpaWtra21tbW9vb3FxcXNzc3V1dXd3d3l5eXt7e319fX9/f0FBQUNDQUVFRUdHR0lJSUtLS01NTU9PT1FRUVJSUlRUVFVVVVXV1dZWVlbW1tdXV1fX19hYWFjY2NlZWVnZ2dpbAAAAAAAAAAAAAAAAAAAAAAA//tQZAAA/wAAP8AAAAIAAAP8AAAAQAAAP8AAAAIAAAP8AAAAQ');
    this.loadSound('emptyGun', 'data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA//tQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAeAAAcLgAHBw4ODhYWFh0dHSUlJS0tLTQ0NDw8PEVFRUFFRUVNTU1VVVVdXV1lZWVtbW11dXV9fX2FhYWNjY2VlZWdnZ2lpaWtra21tbW9vb3FxcXNzc3V1dXd3d3l5eXt7e319fX9/f0FBQUNDQUVFRUdHR0lJSUtLS01NTU9PT1FRUVJSUlRUVFVVVVXV1dZWVlbW1tdXV1fX19hYWFjY2NlZWVnZ2dpbAAAAAAAAAAAAAAAAAAAAAAA//tQZAAA/wAAP8AAAAIAAAP8AAAAQAAAP8AAAAIAAAP8AAAAQ');
    
    // 새로운 효과음 (v0.0.6 추가)
    this.loadSound('bonusHit', 'data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA//tQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAeAAAcLgAHBw4ODhYWFh0dHSUlJS0tLTQ0NDw8PEVFRUFFRUVNTU1VVVVdXV1lZWVtbW11dXV9fX2FhYWNjY2VlZWdnZ2lpaWtra21tbW9vb3FxcXNzc3V1dXd3d3l5eXt7e319fX9/f0FBQUNDQUVFRUdHR0lJSUtLS01NTU9PT1FRUVJSUlRUVFVVVVXV1dZWVlbW1tdXV1fX19hYWFjY2NlZWVnZ2dpbAAAAAAAAAAAAAAAAAAAAAAA//tQZAAA8iUkThBsGGQAAA/wAAABDcCTEcRgYkAAAD/AAAAESUQZBAAA');
    this.loadSound('penaltyHit', 'data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA//tQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAeAAAcLgAHBw4ODhYWFh0dHSUlJS0tLTQ0NDw8PEVFRUFFRUVNTU1VVVVdXV1lZWVtbW11dXV9fX2FhYWNjY2VlZWdnZ2lpaWtra21tbW9vb3FxcXNzc3V1dXd3d3l5eXt7e319fX9/f0FBQUNDQUVFRUdHR0lJSUtLS01NTU9PT1FRUVJSUlRUVFVVVVXV1dZWVlbW1tdXV1fX19hYWFjY2NlZWVnZ2dpbAAAAAAAAAAAAAAAAAAAAAAA//tQZAAA8lMkyBB6GAQAAAvwAAABDKSRIEHgQDgAAC/AAAAE0bRSxBBCI');
    
    // 배경음악 로드
    this.music = new Audio('data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA//tQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAeAAAcLgAHBw4ODhYWFh0dHSUlJS0tLTQ0NDw8PEVFRUFFRUVNTU1VVVVdXV1lZWVtbW11dXV9fX2FhYWNjY2VlZWdnZ2lpaWtra21tbW9vb3FxcXNzc3V1dXd3d3l5eXt7e319fX9/f0FBQUNDQUVFRUdHR0lJSUtLS01NTU9PT1FRUVJSUlRUVFVVVVXV1dZWVlbW1tdXV1fX19hYWFjY2NlZWVnZ2dpbAAAAAAAAAAAAAAAAAAAAAAA//tQZAAA/wAAP8AAAAIAAAP8AAAAQAAAP8AAAAIAAAP8AAAAQ');
    this.music.loop = true;
    this.music.volume = GameSettings.volumes.music;
  },
  
  loadSound(name, url) {
    this.sounds[name] = new Audio(url);
    this.sounds[name].volume = GameSettings.volumes.sfx;
  },
  
  play(name) {
    if (this.sounds[name]) {
      // 사운드 중복 재생 방지를 위해 클론 생성
      const sound = this.sounds[name].cloneNode();
      sound.volume = GameSettings.volumes.sfx;
      sound.play();
    }
  },
  
  playMusic() {
    if (this.music && this.music.paused) {
      this.music.play();
    }
  },
  
  pauseMusic() {
    if (this.music && !this.music.paused) {
      this.music.pause();
    }
  },
  
  setVolume(type, volume) {
    if (type === 'music' && this.music) {
      this.music.volume = volume;
    } else if (type === 'sfx') {
      for (const sound in this.sounds) {
        this.sounds[sound].volume = volume;
      }
    }
  }
};
